apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: samplestorageeu2-gpv2-container
  namespace: default
spec:
  clusterServiceClassExternalName: azure-storage-gpv2-blob-container
  clusterServicePlanExternalName: container
  parameters:
    location: eastus2
    resourceGroup: eu2-resource-group
    parentAlias: sampleserviceeu2
    containerName: sampleserviceeu2container
