apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: sampleserviceeu2-gpv2-binding
  namespace: default
spec:
  instanceRef:
    name: sampleserviceeu2-storage-account
  secretName: sampleserviceeu2-storage-secret
