apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: samplestorageeu2-gpv2-lifecycle
  namespace: default
spec:
  clusterServiceClassExternalName: azure-storage-lifecycle-management-policy
  clusterServicePlanExternalName: policy
  parameters:
    location: eastus2
    resourceGroup: eu2-resource-group
    parentAlias: sampleserviceeu2
    rules:
    - name: firstRule
      enabled: "true"
      definition:
        actions:
          baseBlob:
            delete:
              daysAfterModificationGreaterThan: 180
            tierToCool:
              daysAfterModificationGreaterThan: 29
            tierToArchive:
              daysAfterModificationGreaterThan: 179
          snapshot:
            delete:
              daysAfterCreationGreaterThan: 45
        filters:
          blobTypes:
            - blockBlob
          prefixMatch:
            - container1/match1
            - container2/match2
            


